### PR TITLE
Remove configuration for disabling user indexes in MZ

### PR DESCRIPTION
**Pull request by sploiselle**
This is going away as part of MaterializeInc/materialize#12412, so I science dogged removing the option from this repo, as well. Please holler if I've mangled anything and let me know how to run local tests (found `bin/gen` but can't get python to work).

### CODE REVIEW

**Comment by alex-hunt-materialize** [comment]
This is actually the SDK for the old "deployments", not the new platform stuff. The openapi schema is generated from the code in the cloud repo. If we want to remove this, which I don't think we do yet, we should probably remove it from the API in the cloud repo first.

**Comment by sploiselle** [comment]
This repo's still in use in the MZ repo https://github.com/MaterializeInc/materialize/blob/main/src/mzcloud-cli/src/bin/mzcloud.rs#L400; if this is deprecated, cool if we merge this PR to remove the vestigial field from `mzcloud-cli`?

**Comment by alex-hunt-materialize** [comment]
The mcloud-cli also only currently works with the old deployments stuff, which AFAIK still supports disable user indexes mode.

**Comment by sploiselle** [comment]
Ok, so would you cosign cherry-picking a change to the on-prem-capable version of MZ that depends on a branch of this repo that reflects the current `main`, and then `main` can contain this commit and we can remove the config options from the `main` branch of MZ?

**Comment by benesch** [comment]
I think we can actually basically abandon this repository since these SDKs won't be needed by the new version of the CLI. @sploiselle I think the right thing to do here is to delete the code from mzcloud-cli on `main` that allows managing deployments. Users who want to manage legacy deployments from the mzcloud CLI (not that there are any, but in theory) can do so by using the v0.26 branch.

**Comment by sploiselle** [comment]
@benesch ty, will do!

**Pull request closed without merging**
